### ISSUE TITLE
Decrease initialisation time for large nested grids

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#820]
@martinschorb @constantinpape 

I improved the code for loading large grids quite a bit (not on any update site yet as other things are not yet working in the respective branch).
 
However, for nested grid views it still needs to load the metadata from one reference image in each of the nested grids, which, for the HTM case, still amounts to quite a lot of images.
In principle this could be avoided, if the code would know that it can reuse the metadata from one of the images that have been loaded already. I wonder now whether and how to implement this. 

We _could_ add something to the spec for the `mergedGrid` like:

`metadataSource: ...`  and there point to one image that contains the metadata. Like this all the nested grids could fetch the metadata from the same image, which would dramatically decrease initialization time. 

What do you think?

**Comment by constantinpape** [comment]
In principle this sounds good, but I guess we only need this for nested merged grids, right?
So this field should be optional and a simplified version could look like this:
```yaml
{"sourceTransforms": [
 {"mergedGrid": {  # the first image grid, we don't have a reference source
     "sources": ["imageA", "imageB"],
     "mergedGridName": "gridA"
 }},
 {"mergedGrid": {  # the second image grid, we don't have a reference source
     "sources": ["imageC", "imageD"],
     "mergedGridName": "gridB"
 }},
 {"mergedGrid": {  # the nested grid, we have a reference source
     "sources": ["gridA", "gridB"],
     "mergedGridName": "nestedGrid",
     "metadataSource": "imageA"
 }},
]}
```
If this is what you have in mind then it's easy to add to the spec.

**Comment by tischi** [comment]
I think we also need it for the not nested ones (also see may other comments).

```yaml
{"sourceTransforms": [
 {"mergedGrid": {  # the first image grid, we don't have a reference source
     "sources": ["imageA", "imageB"],
     "mergedGridName": "gridA",
     "metadataSource": "imageA"
 }},
 {"mergedGrid": {  # the second image grid, we don't have a reference source
     "sources": ["imageC", "imageD"],
     "mergedGridName": "gridB",
     "metadataSource": "imageA" # note that this is not part of this `mergedGrid`, but this is fine. important is to reuse the same as much as possible
 }},
 {"mergedGrid": {  # the nested grid, we have a reference source
     "sources": ["gridA", "gridB"],
     "mergedGridName": "nestedGrid",
     "metadataSource": "imageA" # In fact, this is likely wrong, because it does not have the correct metadata
     "metadataSource": "gridA" # this would work
 }},
]}
```
